- src/lib/strategies/Shared.ts
Why did the previous code work PERFECTLY FINE when run with Node.js, but BORKED in debugger, is something I don't understand.
Nevertheless...
(RTX ON PIECES, OH YEAH!)
> fix(loader): compare constructors instead of prototypes

- src/index.ts
- src/lib/shared/Container.ts
- src/lib/strategies/LoaderStrategy.ts
- src/lib/structures/Piece.ts
- src/lib/structures/Store.ts
- **BREAKING CHANGE**: Renamed `PieceContextExtras` to `Container`, usage and augmentation is the same.
- **BREAKING CHANGE**: Removed `Store.injectedContext`, use globally exported `container` variable instead.
- **BREAKING CHANGE**: Renamed `Store#context` to `Store#container`.
- **BREAKING CHANGE**: Renamed `Piece#context` to `Piece#container`.
> refactor: minor naming changes for consistency with ecosystem

- src/lib/strategies/ILoaderStrategy.ts
- src/lib/strategies/LoaderStrategy.ts
- src/lib/structures/Store.ts
Also removed an instance of `Map#clear`, which resulted on pieces to be removed but not unloaded, which causes issues specially with /framework's listeners.
> feat(store): add `unloadAll`

- src/lib/strategies/LoaderStrategy.ts
Extend ts-node support by allowing pieces to add .ts to the supported extensions even when using ts-node through the ts-node-dev package.
Thanks @Favna
> feat(ts-node-dev-support): check if env variable is set

- src/index.ts
- src/lib/strategies/ILoaderStrategy.ts
- src/lib/structures/AliasPiece.ts
- src/lib/structures/Piece.ts
- src/lib/structures/PieceLocation.ts
- src/lib/structures/Store.ts
- Added `PieceLocation`.
- **AliasPiece**: strict type `toJSON()`.
- **ILoaderStrategy**: Added `HydratedModuleData` type.
- **Piece**: added `location` property, containing the file's metadata.
- **Piece**: strict type `toJSON()`.
- :warning: **BREAKING CHANGE**: Changed `Store#load` to take `root` and `path`.
- :warning: **BREAKING CHANGE**: Make `ILoaderStrategy#load` take `HydratedModuleData`.
- :warning: **BREAKING CHANGE**: Remove `Piece#path`, use `#location` instead.
> refactor: update to v3

- package.json
Yarn v3 no longer has the `--latest` flag. [docs](https://yarnpkg.com/cli/upgrade-interactive)
> fix: remove unsupported yarn flag

- package.json
- src/lib/structures/AliasPiece.ts
- src/lib/structures/Piece.ts
- yarn.lock
After and if this is merged, I'll create a PR in `/framework` to add namespaces to `Command`, `Listener`, and `Argument`, and migrate the use of all of the affected interfaces/enums to using the namespace.
> style: create namespaces for `Piece` and `AliasPiece`

- src/lib/shared/Container.ts
Current example explains how to inject the `client` property in container which is invalid because it's already available in `container`. Replaced it with simple example to not create confusion.
> chore: fix container extend example

- src/lib/strategies/LoaderStrategy.ts
- src/lib/strategies/Shared.ts
- src/lib/structures/Store.ts
This will allow us to do `super(Command, { name: 'commands' })` without `as any`.
> fix(store): support abstract classes

- src/lib/internal/Path.ts
- src/lib/structures/Store.ts
- src/lib/structures/StoreRegistry.ts
This way, URLs can be used without calling `fileURLToPath`.
> feat: add URL support for register methods

- src/lib/strategies/LoaderStrategy.ts
ESM pieces can now use `import.meta.url.searchParams.get('name')` to get the name of the file (without extension) as well as `import.meta.url.searchParams.get('extension')` to get the file extension.
> feat(esm): add more qs parameters

- src/lib/strategies/LoaderStrategy.ts
This PR fixes the issue that ESModule `.ts` files fail to be loaded and `.cts` / `.mts` files are not recognized when using [`ts-node`](https://www.npmjs.com/package/ts-node) or any of TypeScript executors.
Currently, the following errors occur if you run `ts-node` when your project was written in and set to ESModule:
```
Error when loading 'C:\Dev\my-bot\src\interaction-handlers\hello.ts': Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Dev\my-bot\src\interaction-handlers\hello.ts
require() of ES modules is not supported.
require() of C:\Dev\my-bot\src\interaction-handlers\hello.ts from C:\Dev\my-bot\node_modules\.pnpm\@sapphire+pieces@3.5.2\node_modules\@sapphire\pieces\dist\lib\strategies\LoaderStrategy.js is an ES module file as it is a .ts file whose nearest parent …
```
> feat: support loading ESModule TS files when using ts-node

- src/lib/strategies/LoaderStrategy.ts
While this is technically a breaking change, it's unlikely it affects anyone.
I'm also aware users can just extend `LoaderStrategy` to ignore files following naming schemes of their liking, however, none of this is documented, and it would be considered a very advanced topic, as it falls under the innermost core part of Sapphire.
This patch adds a little feature to exclude files which name start with `_` from being loaded. This comes with two large somewhat-common uses:
- **Partial logic-only files**:
For example, consider a `reminder.ts` command that has several (≥6) subcommands, and each run very complex code, making the command have over 400 lines of code. With this feature, users will now be able to define `_reminder-add.ts`, `_reminder-delete.ts`, and so on, to split the subcommands …
> feat: omit files starting with `_` from loading

- src/lib/strategies/Shared.ts
- `ctor.constructor` is `Function`
- `base.constructor` is `Function`
They're not `Function` when they're instances of a class, but since we are comparing the constructors, their constructors are `Function`, since classes are basically functions, as such, the utility was always returning `true` for anything that is a class.
With this change, we're not longer comparing `Function`s, but rather, the classes themselves, and now it does load pieces only if compatible instances were found:
> fix: resolve issue with class extends utility

- src/lib/strategies/LoaderStrategy.ts
Without this, extending `LoaderStrategy` wouldn't the extended class to have the arguments in the `onLoad`, `onLoadAll`, `onUnload`, and `onUnloadAll` methods.
> fix(LoaderStrategy): overload empty methods for extensions

- src/index.ts
- src/lib/errors/LoaderError.ts
- src/lib/internal/constants.ts
- src/lib/structures/PieceLocation.ts
- src/lib/structures/Store.ts
- src/lib/structures/StoreRegistry.ts
Adds a new method, `container.stores.loadPiece()`, which loads or queues a piece into the piece registries. Useful specially for running Sapphire bots in environments where FS is limited or unavailable.
Usage example:
```typescript
import { Command, container } from '@sapphire/framework';
class PingCommand extends Command {
// ...
}
container.stores.loadPiece({
store: 'commands',
name: 'ping',
piece: PingCommand
});
```
The `virtual` name was chosen as an inspiration to Vue's virtual modules, where they create dynamic modules prefixed with `virtual:`.
> feat(StoreRegistry): add queue and virtual file support

- src/lib/structures/AliasStore.ts
Found while updating https://github.com/sapphiredev/framework/pull/686 to use the new `StoreName` type parameter
> fix(AliasStore): pass `StoreName` type parameter to `Store`

- src/lib/structures/AliasPiece.ts
- src/lib/structures/Piece.ts
- src/lib/structures/StoreRegistry.ts
With this PR, `Piece#store` is now typed as `StoreOf<StoreName>`, which means that by passing a second type parameter in the piece's class, `StoreName`, the type gets strictly typed as the store that contains it. For example, in Framework, `StoreOf<'commands'>` returns `CommandStore`, and `PieceOf<'commands'>` returns `Command<Args, CommandOptions>`,
> feat(StoreRegistry): add `StoreOf` and `PieceOf`

- src/lib/structures/AliasPiece.ts
- src/lib/structures/AliasStore.ts
- src/lib/structures/Piece.ts
- src/lib/structures/Store.ts
- src/lib/structures/StoreRegistry.ts
> feat: use `StoreName` for improved type experience

- src/lib/structures/AliasPiece.ts
- src/lib/structures/Piece.ts
As there are framework pieces with name clash (`Argument.Context` for example isn't `Piece.Context`, but `ArgumentContext`).
> refactor: rename `Piece.Context` to `Piece.LoaderContext`

- src/lib/structures/Store.ts
- src/lib/structures/StoreRegistry.ts
Fixes ONE of the issues with Deno >.>
The others we cannot fix as they're at the runtime's control
> fix: make virtual pieces respect name restrictions like normal pieces

- src/lib/strategies/LoaderStrategy.ts
- src/lib/strategies/env.ts
Added the following:
- `@babel/node`
- `@swc/cli`
- `esbuild`
- `jest`
- `tsm`
- `tsx`
- `vitest`
On top of the existing:
- Deno
- Bun
- `ts-node`
Code based on https://github.com/fastify/fastify-autoload/blob/master/runtime.js
> feat: check for more environments for TS support

- src/lib/strategies/env.ts
Added
- function `checkPreloadModulesSubstring`
Small fix for TS environment support. `tsx` has to be searched as a substring when it's present in `process._preload_modules` as the string takes a form similar to:
```js
['path_to_project_or_npm/node_modules/tsx/dist/preflight.cjs']
```
Function may be used in the future by modules similarly loaded like this.
> fix: fixed checking for tsx support

- src/lib/internal/RootScan.ts
This pull request includes changes to the `src/lib/internal/RootScan.ts` file to enhance the detection of project type by checking for the presence of a Deno configuration file.
Enhancements to project type detection:
* [`src/lib/internal/RootScan.ts`](diffhunk://#diff-185d0a50c8603a9e51efb1af56d9f33f9688f896199998586f926ba07b8dbe9bL1-R1): Added `existsSync` import from the `fs` module to check for the presence of the `deno.json` file.
* [`export function parseRootData()`](diffhunk://#diff-185d0a50c8603a9e51efb1af56d9f33f9688f896199998586f926ba07b8dbe9bL85-R86): Modified the function to return `{ root: cwd, type: 'ESM' }` if `deno.json` is found, otherwise return `{ root: cwd, type: 'CommonJS' }`.
Closes #474
> fix(RootScan): check for runtime config files when checking for CJS vs ESM
